[package]
name = "exchange-types"
version = "0.4.16"
edition = "2024"

[dependencies]
query-params = { version = "1.0.2", registry = "shipyard" }
rust_decimal = "1.42.1"
serde = { version = "1.0.228", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
serde_with = { version = "3.21.0", optional = true }
strum = { version = "0.28.0", features = ["derive"] }

[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_with", "rust_decimal/serde", "dep:serde_json"]

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
features = []
no-deps = true
targets = ["x86_64-unknown-linux-gnu"]
